kind: pipeline
name: default

steps:
- name: frontend
  image: node
  commands:
  - npm install
  - npm test
  when:
    branch:
    - ci


- name: upload
  image: plugins/s3
  settings:
    bucket: static
    # access_key: 
    # secret_key: 
    source: public/**/*
    target: /react
    path_style: true
    endpoint: https://minio.leble.ink