kind: pipeline
name: default

steps:
- name: restore-cache
  image: drillster/drone-volume-cache
  restore: true
  mount:
    - node_modules
  volumes:
    - /tmp/cache:/cache

- name: install
  image: node
  commands:
  - npm install

- name: rebuild-cache
  image: drillster/drone-volume-cache
  rebuild: true
  mount:
    - node_modules
  volumes:
    - /tmp/cache:/cache

- name: test
  image: node
  commands:
  - npm test

- name: upload
  image: plugins/s3
  settings:
    bucket: static
    access_key: 
      from_secret: s3_access_key
    secret_key: 
      from_secret: s3_secret_key
    source: public/**/*
    target: /
    path_style: true
    endpoint: http://srv-minio:9000