kind: pipeline
name: default

steps:
- name: install
  image: node
  commands:
  - npm install

- name: test
  image: node
  commands:
  - npm test

- name: upload
  image: plugins/s3
  settings:
    bucket: static
    access_key: 
      from_secret: s3_access_key
    secret_key: 
      from_secret: s3_secret_key
    source: public/**/*
    target: /
    path_style: true
    endpoint: http://srv-minio:9000